########################### NETWORKS
networks:
  media_network:
    name: media_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
 
include:
  ########################### SERVICES
  # PREFIX udms = Ultimate Docker Media Server
  # HOSTNAME=udms - defined in .env
 
  # CORE
  - compose/$HOSTNAME/socket-proxy.yml
  - compose/$HOSTNAME/portainer.yml
  - compose/$HOSTNAME/dozzle.yml
  - compose/$HOSTNAME/homepage.yml
  # INDEXERS
  - compose/$HOSTNAME/prowlarr.yml
  # MEDIA
  - compose/$HOSTNAME/jellyfin.yml
  # DOWNLOADERS
  - compose/$HOSTNAME/qbittorrent.yml
  # - compose/$HOSTNAME/sabnzbd.yml
  # PVRS
  - compose/$HOSTNAME/radarr.yml
  - compose/$HOSTNAME/sonarr.yml
  - compose/$HOSTNAME/lidarr.yml
  - compose/$HOSTNAME/readarr.yml
  # COMPLEMENTARY APPS
  - compose/$HOSTNAME/bazarr.yml
  # UTILITIES
  - compose/$HOSTNAME/filebrowser.yml
  # MAINTENANCE
  - compose/$HOSTNAME/docker-gc.yml
  # PICTURE
  - compose/$HOSTNAME/immich.yml

