services:
  # Bazarr - Subtitle Management
  # Guide: https://www.youtube.com/watch?v=8vZ95HOdT-I
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      media_network:
          ipv4_address: ${BAZARR_IP}
    ports:
      - "${BAZARR_PORT}:6767"
    volumes:
      - $DOCKERDIR/appdata/bazarr:/config
      - $DATADIR/media/movies:/data/movies
      - $DATADIR/media/tv:/data/tv
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

