services:
  # Homepage - Application Dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["apps", "all"]
    networks:
      socket_proxy:
        ipv4_address: ${HOMEPAGE_SOCKET_IP}
      media_network:
        ipv4_address: ${HOMEPAGE_IP}
    ports:
      - "${HOMEPAGE_PORT}:3000"
    volumes:
      - $DOCKERDIR/appdata/homepage:/app/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_ALLOWED_HOSTS: "localhost,127.0.0.1,${HOMEPAGE_IP}:${HOMEPAGE_PORT},${HOMEPAGE_SOCKET_IP}:${HOMEPAGE_PORT}"
