services:
  # Jellyfin - Media Server
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    networks:
      media_network:
          ipv4_address: ${JELLYFIN_IP}
    security_opt:
      - no-new-privileges:true
    restart: "no"
    # profiles: ["media", "all"]
    user: $PUID:$PGID
    devices:
      - /dev/dri:/dev/dri # for harware transcoding
    ports:
      - "${JELLYFIN_PORT}:8096"
      # - "8920:8920" # Emby also uses same port if running both
    environment:
      UMASK_SET: 022
      TZ: $TZ
    volumes:
      - $DOCKERDIR/appdata/jellyfin:/config
      - $DATADIR/media:/data
      - $DATADIR/downloads:/t_downloads
      # - $DATADIR/usenet:/u_downloads
      - $TRANSCODE:/transcode
