services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest 
    container_name: radarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      media_network:
        ipv4_address: ${RADARR_IP}
    ports:
      - "${RADARR_PORT}:7878"
    volumes:
      - $DOCKERDIR/appdata/radarr:/config
      
      # Thư viện phim (nơi radarr sẽ move các phim sau khi tải)
      - $DATADIR/media/movies:/data/movies
      
      # Nơi SABnzbd và qBittorrent lưu file tải về (cần trùng đường dẫn trong app kia)
      - $DATADIR/downloads:/data/downloads
      
      # Option: đồng bộ timezone hệ thống
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UMASK_SET: 002

