services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      media_network:
        ipv4_address: ${SONARR_IP}
    ports:
      - "${SONARR_PORT}:8989"
    volumes:
      - $DOCKERDIR/appdata/sonarr:/config
      - $DATADIR/media/tv:/data/tv
      - $DATADIR/downloads:/data/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UMASK_SET: 002

