services:
  unbound:
    container_name: unbound
    image: "mvance/unbound:latest"
    restart: unless-stopped
    networks: 
     macvlan_net:
       ipv4_address: $UNBOUND_IP
    volumes:
      - $DOCKERDIR/appdata/unbound:/opt/unbound/etc/unbound
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
